// Generated by sim/export_champion.mjs from a sim/tune.mjs self-play run -- do not edit.
export const TUNED_WEIGHTS = {
    "xeStored": 8.257,
    "xeInHand": 5.11,
    "junkInHand": 3.513,
    "money": 0.51,
    "contractDone": 8.076,
    "costWeight": 0.55,
    "buyThreshold": 1.2,
    "installVp": 3.565,
    "contractVp": 1.129,
    "contractMoney": 0.563,
    "contractXe": 2.064,
    "instantContract": 5.028,
    "pipeline": [
        6.292,
        6.834,
        5.761
    ],
    "wipeMinMoney": 16.122,
    "wipeBelowValue": 1.024,
    "upgrade": {
        "heat_exchanger": 4.56,
        "molecular_sieve": 4.191,
        "desiccant_bed": 3.754,
        "cold_turbine": 1.253,
        "packed_tower": 2.169,
        "sales_director": 6.9,
        "spotless_audit": 4.307,
        "reserve_fund": 3.276,
        "deal_maker": 1.921,
        "floor_broker": 1.263,
        "account_manager": 3.863,
        "sampling_port": 3.172,
        "cryo_chiller": 2.539,
        "gas_reclaimer": 1.227,
        "flow_regulator": 2.922,
        "shift_engineer": 1.8,
        "freelance_fitter": 2.478,
        "procurement_agent": 1.367
    }
};
